tz-14
GeiseR98/java-shareit pull request #2
Opened 2023-06-22 18:33 UTC by GeiseR98

2023-06-22 20:22 UTC, db-exp requested changes

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @Column(name = "email", nullable = false)
тоже можно Size добавить

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
тоже можно Size добавить

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
лучше использовать "чужие" сервисы, а не "чужие" репозитории, чтобы уменьшить связность

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String name;
тоже можно Size добавить

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String description;
тоже можно Size добавить

2023-06-22 20:22 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private String text;
тоже можно Size добавить

2023-06-22 21:16 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private String text;
добавил валидацию в Dto

2023-06-22 21:16 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String description;
уже есть валидация в Dto

2023-06-22 21:17 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String name;
уже есть валидация в Dto

2023-06-22 21:17 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
добавил валидацию в Dto

2023-06-22 21:17 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @Column(name = "email", nullable = false)
добавил валидацию в Dto

2023-06-22 21:47 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceImpl.java
> +    private final BookingRepository bookingRepository;
Принял, в примерах что нам давали везде "портировали" именно репозитории...

2023-06-22 21:55 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @Column(name = "email", nullable = false)
Более того, она ограничена в создании БД..

2023-06-22 21:55 UTC, GeiseR98 commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
Более того, она ограничена в создании БД..

2023-06-23 07:22 UTC, db-exp approved these changes

2023-06-27 19:44 UTC, merged