Add docker
GeiseR98/java-shareit pull request #4
Opened 2023-07-05 02:20 UTC by GeiseR98

2023-07-07 19:16 UTC, db-exp requested changes

2023-07-07 19:16 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
лучше взять значение из переменной среды (указывается в docker-compose) ${Имя_переменной}

2023-07-07 19:16 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
тоже можно использовать переменную среды

2023-07-07 22:40 UTC, GeiseR98 commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
готово

2023-07-07 22:41 UTC, GeiseR98 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
готово

2023-07-08 20:12 UTC, db-exp approved these changes

2023-09-03 21:49 UTC, merged